export const testimonials = [
    {
      name: "Mostakim Hossain",
      role: "Full Stack Developer",
      rating: 5,
      text: "Insurea has been a game changer for me. Their dedication to customer service and quick response really impressed me. Highly recommended!",
      avatar: "../../public/p1.avif",
      cardType: "white",
    },
    {
      name: "Sadia Afroz",
      role: "Marketing Specialist",
      rating: 4,
      text: "I loved how easily I was able to get the right insurance plan. The team was super supportive and answered all my queries politely.",
      avatar: "../../public/p2.avif",
      cardType: "teal",
    },
    {
      name: "Rafiul Islam",
      role: "E-commerce Entrepreneur",
      rating: 4,
      text: "Running a business is stressful, but Insurea’s support has been a blessing. Their plans are both affordable and reliable.",
      avatar: "../../public/p3.avif",
      cardType: "white",
    },
    {
      name: "Mehnaz Tabassum",
      role: "Medical Officer",
      rating: 5,
      text: "Their healthcare coverage met all my professional needs. The experience felt personalized and trustworthy. Highly satisfied!",
      avatar: "../../public/p4.avif",
      cardType: "teal",
    },
    {
      name: "Tanvir Chowdhury",
      role: "Freelance Designer",
      rating: 5,
      text: "What stood out to me was their communication and flexibility. Truly a customer-first approach, very rare these days.",
      avatar: "../../public/p5.avif",
      cardType: "white",
    },
    {
      name: "Shamima Nasrin",
      role: "Teacher",
      rating: 4,
      text: "Insurea made everything very smooth. It was easy to understand the policies and their staff were kind and patient.",
      avatar: "../../public/p1.avif",
      cardType: "teal",
    },
    {
      name: "Nayeem Ahmed",
      role: "Software Engineer",
      rating: 5,
      text: "Very efficient service and transparent policy details. I’ve already recommended Insurea to many of my colleagues.",
      avatar: "../../public/p6.avif",
      cardType: "white",
    },
    {
      name: "Farzana Rahman",
      role: "NGO Coordinator",
      rating: 4,
      text: "Their team worked with us closely to understand our requirements. A very professional and honest service provider.",
      avatar: "../../public/p1.avif",
      cardType: "teal",
    },
  ];
  